custom:
  dronespots:
    db:
      driverClassName: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/dronespots
      user: dronespots
      # password: dev
    oauth:
      clientId: dronespots
      clientSecret: dev
    mapbox:
      accessToken: dev
    
spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto: update
          show_sql: false
        connection:
          autocommit: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
          
logging:
  level:
    root: INFO
    org:
      hibernate: INFO

server:
  port : 5090
